/*
 * Copyright (c) 2019, Hiram K.
 * All rights reserved.
 *
 */
package com.ct.views;

import java.awt.Frame;

/**
 *
 * @author Hiram K.
 */
public class MainWindow extends javax.swing.JFrame {

    private static final long serialVersionUID = -3077898430347351322L;

    /** Creates new form MainWindow */
    public MainWindow() {
        super();
        //Open the window in its maximized state
        super.setExtendedState(Frame.MAXIMIZED_BOTH);
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        eventMenuItem = new javax.swing.JMenuItem();
        customerMenuItem = new javax.swing.JMenuItem();
        reportsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        menu.setText("Menu");

        eventMenuItem.setText("Event");
        menu.add(eventMenuItem);

        customerMenuItem.setText("Customer");
        menu.add(customerMenuItem);

        reportsMenuItem.setText("Reports");
        menu.add(reportsMenuItem);

        menuBar.add(menu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 332));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem customerMenuItem;
    private javax.swing.JMenuItem eventMenuItem;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem reportsMenuItem;
    // End of variables declaration//GEN-END:variables
}
